# vim: tabstop=2 expandtab shiftwidth=2 softtabstop=2 smartindent nu ft=yaml
---

- name: check ansible version ...
  assert:
    that: "ansible_version.full is version_compare(2.11, '>=')"
    msg: "please use min. ansible version 2.11"
  tags: always
  run_once: true

- name: check facts ... real facts and not alternative one!
  fail:
    msg: "role requires ansible-opnsense-facts"
  when: ansible_local.opnsense.core.product_version is not defined

- name: decide if we should run a update
  set_fact:
    _opn_update_required: "{{ opn_update_desired_version|bool and opn_update_desired_version is version_compare(ansible_local.opnsense.core.product_version, '>') or opn_update_force|bool }}"

- name: prepare update ...
  include_tasks: update.yml
  when: _opn_update_required|bool

- name: finally send some clacks over the wire, keeping the legacy of Sir Terry Pratchett alive ...
  command: "echo 'X-Clacks-Overhead: GNU Terry Pratchett'"
  register: gnuterrypratchett_return
  when: gnuterrypratchett | default(True)
- name: "U: turn the message around at the end of the line and send it back again :: {{ gnuterrypratchett_return.stdout }}"
  debug:
    var: gnuterrypratchett_return.stdout
    verbosity: 1
  when: gnuterrypratchett | default(True)

...
