---
- name: create snapshot {{ opn_snapshot_name }}  # noqa no-changed-when
  ansible.builtin.command: "configctl zfs snapshot create {{ opn_snapshot_name }}"
  register: _zfs_snapshot_create

- name: ... parse output
  ansible.builtin.set_fact:
    _zfs_snapshot_created_status: "{{ _zfs_snapshot_create.stdout | from_json }}"
  when: not ansible_check_mode

- name: print output of create snapshot {{ opn_snapshot_name }}
  ansible.builtin.debug:
    var: _zfs_snapshot_created_status
  when: not ansible_check_mode

- name: assert snapshot {{ opn_snapshot_name }} was created
  ansible.builtin.assert:
    that: _zfs_snapshot_created_status.status | lower == 'ok' or (opn_zfs_snapshot_ignore_error | bool)
    msg: create snapshot failed
  when: not ansible_check_mode
