---

- name: check zfs snapshot support  # noqa no-changed-when
  ansible.builtin.assert:
    that:
      - ansible_local.opnsense.zfs_snapshot.supported.status is defined
      - ansible_local.opnsense.zfs_snapshot.supported.status == 'OK'
    msg: "ZFS snapshots are not supported on the current system"

